-- CREATE DATABASE focus-todo DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;

USE focus-todo;

CREATE TABLE collections (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(64) NOT NULL,
  tasks INT NOT NULL DEFAULT 0
);

CREATE TABLE tasks (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  task VARCHAR(64) NOT NULL,
  is_complete TINYINT(1) NOT NULL DEFAULT 0,
  created DATETIME NOT NULL DEFAULT NOW(),
  last_updated DATETIME NOT NULL DEFAULT NOW() ON UPDATE NOW(),
  collection INT NOT NULL REFERENCES collections(id)
);